DADOS_DIR = "dados"
CHROMA_DIR = "db"
COLLECTION_NAME = "RAG_FOR_AI_ARCHITECTS"

CHUNK_SIZE = 600
CHUNK_OVERLAP = 80

EMBEDDING_MODEL = "nomic_embed_text"
LLM_MODEL = "mistral"

TOP_K = 5
SIMILARITY_THRESHOLD = 0.3

OLLAMA_BASE_URL = "http://localhost:11434"