from typing import List, Dict, Any

import requests

from config import LLM_MODEL, OLLAMA_BASE_URL
from src.retrieval import format_context



SYSTEM_PROMPT = """Você é um assistente especializado em Engenharia de IA, MLOps, LLMs e automação com n8n.

Suas regras:
1. Responda APENAS com base no contexto fornecido entre as tags <contexto> e </contexto>
2. Se o contexto não contiver informação suficiente, diga claramente: "Não encontrei essa informação na base de conhecimento."
3. Sempre mencione a(s) fonte(s) que embasaram sua resposta no final (seção "Fontes")
4. Seja preciso, didático e objetivo
5. Use markdown para organizar respostas longas (listas, negrito, blocos de código)
6. Responda no mesmo idioma da pergunta"""


def build_prompt(query: str, context: str) -> str:
    """
    Mounts the final prompt in the expected format for Mistral Instruct.
    Structure:
        - System prompt with the rules
        - Retrieved context delimited by XML tags
        - User question

    The context delimiter <context> helps the model to clearly 
    separate what is instruction from what is factual information.
    """
    return f"""{SYSTEM_PROMPT}

<context>
{context}
</context>

Question: {query}

Answer:"""


def generate_answer(
    prompt: str,
    temperature: float = 0.2,
    max_tokens: int = 1500
) -> str:
    """
    Sends the prompt to Mistral via Ollama API and returns the response.

    Parameters:
      - temperature=0.2: low randomness → more deterministic and factual answers
        (for RAG, low temperature is preferable to avoid hallucinations)
        Increase to 0.7+ if you want more creative/varied responses
    Args:
        prompt:      Full prompt (system + context + question)
        temperature: Controls randomness (0.0 = deterministic, 1.0 = creative)
        max_tokens:  Limit of tokens in the response

    Returns:
        Text of the answer generated by Mistral
    """
    payload = {
        "model": LLM_MODEL,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": temperature,
            "num_predict": max_tokens,
            "top_p": 0.9,
            "repeat_penalty": 1.1  # penaliza repetição de frases
        }
    }

    ans = requests.post(
        f"{OLLAMA_BASE_URL}/api/generate",
        json=payload,
        timeout=120
    )
    ans.raise_for_status()
    return ans.json()["response"].strip()


def answer_query(
    query: str,
    chunks: List[Dict[str, Any]],
    temperature: float = 0.2,
    verbose: bool = True
) -> Dict[str, Any]:
    """
    Main function of step 5:
      1. Formats the chunks into readable context
      2. Builds the optimized prompt
      3. Calls Mistral
      4. Returns the answer + traceability metadata

    Args:
        query:       Original user question
        chunks:      Chunks retrieved in step 4
        temperature: Generation parameter
        verbose:     If True, prints the process

    Returns:
        Dict with:
          - answer:   Text generated by Mistral
          - fonts:     List of files used as context
          - n_chunks:   Number of chunks used
          - query:   Original question (for logging)
    """

    if not chunks:
        return {
            "answer": "Não encontrei informações relevantes na base de conhecimento para responder essa pergunta.",
            "fonts": [],
            "n_chunks": 0,
            "query": query
        }

    context = format_context(chunks)
    prompt = build_prompt(query, context)

    if verbose:
        print(f"  Generating answer with '{LLM_MODEL}' (temp={temperature})...")
        print(f"   Context: {len(chunks)} chunks | {len(context):,} chars\n")

    answer = generate_answer(prompt, temperature=temperature)

    fonts = sorted(set(c["source"] for c in chunks))

    return {
        "answer": answer,
        "fonts": fonts,
        "n_chunks": len(chunks),
        "query": query
    }


def print_result(result: Dict[str, Any]) -> None:
    """Exhibits the final result formatted in the terminal."""
    print(f" Question: {result['query']}")
    print(f"\n{result['answer']}\n")
    print()
    print(f"📎 Fontes utilizadas ({result['n_chunks']} chunks):")
    for f in result["fonts"]:
        print(f" {f}")
    print()